name: Train Loan Model

on:
  push:
    paths:
      - model-demo/**
      - .github/workflows/train-model.yml
      - requirements.txt

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        working-directory: ./model-demo
        run: python model.py

      - name: Genrate tag
        id: version
        run: |
          VERSION="v$(date +%Y%m%D%H%M%S)"
          echo "VERSION=$VERSION" > $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model-demo/model.pkl


      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: "Automated release"

      - name: Upload version file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: model-demo/model.pkl
          asset_name: model.pkl
          asset_content_type: application/octet-stream

          
